export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_GATOS_PENDING = 'REQUEST_GATOS_PENDING'
export const REQUEST_GATOS_FAILED  = 'REQUEST_GATOS_FAILED'
export const REQUEST_GATOS_SUCCESS = 'REQUEST_GATOS_SUCCESS'

export const POST_GATO_PENDING = 'POST_GATO_PENDING'
export const POST_GATO_FAILED  = 'POST_GATO_FAILED'
export const POST_GATO_SUCCESS = 'POST_GATO_SUCCESS'


export const REQUEST_GATO_BY_ID_PENDING = 'REQUEST_GATO_BY_ID_PENDING'
export const REQUEST_GATO_BY_ID_FAILED  = 'REQUEST_GATO_BY_ID_FAILED'
export const REQUEST_GATO_BY_ID_SUCCESS = 'REQUEST_GATO_BY_ID_SUCCESS'

export const POST_COMMENT_PENDING = 'POST_COMMENT_PENDING'
export const POST_COMMENT_FAILED  = 'POST_COMMENT_FAILED'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'

export const SET_LANGUAGE = 'SET_LANGUAGE'